name: "build"
run-name: ${{ inputs.tag }}

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: image tag
        default: "0.0.1"

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64 #,linux/arm64
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        run: |
          docker buildx build --push --platform linux/amd64 -t mintlimes/c-erp:${{ inputs.tag }} .
      - name: Deploy ERP
        env:
          RELEASE: erp
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          URL: erp.srmvcas.org
          DB_HOST: postgres.postgres
          DB_PORT: "5432"
          DB_USERNAME: crp
          DB_PASSWORD: ${{ secrets.SRMVCAS_DB_PASSWORD }}
          DB_DB: crp
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          IMAGE_TAG: ${{ inputs.tag }}
        run: |
          bash deploy.sh
