name: "build"
run-name: ${{ inputs.tag }}

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: image tag
        default: "0.0.1"

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64 #,linux/arm64
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        run: |
          docker buildx build --push --platform linux/amd64 -t mintlimes/c-erp:${{ inputs.tag }} .
      # - name: Create Release
      #   uses: actions/create-release@latest
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.KESHORE_SA_FULLACCESS }}
      #   with:
      #     tag_name: ${{ inputs.tag }}
      # - name: Deploy SRMVCAS
      #   env:
      #     KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      #   run: |
      #     echo "$KUBE_CONFIG" | base64 -d > /tmp/config
      #     export KUBECONFIG=/tmp/config
      #     helm \
      #     upgrade --install erp \
      #     --set image.tag=${{ inputs.tag }} \
      #     --debug \
      #     -n erp --create-namespace \
      #     ./helm/erp
